### ISSUE TITLE
Achieving SAI_STATE_EXPLORE after resting while being unable to move soft-locks the game

### ISSUE THREAD

**Issue by SkoobyDoo** [SkoobyDoo/tome4-SkooBot#46]
https://pastebin.com/2bikwuB9

![image](https://user-images.githubusercontent.com/9893941/54080559-951a2100-42a7-11e9-90bd-f2d8360af040.png)

**Comment by SkoobyDoo** [comment]
Resolved by b9ec448e79fba191fe05b298ff422f09e6d4f59f

**Comment by h-youhei** [comment]
With Base Game v1.7.2 and Skoobot v0.0.12, the soft-locks still occur.

When I get asleep, playing melee character.
